// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package agent

import (
	greeting2 "github.com/kappusuton-yon-tebaru/backend/cmd/agent/internal/greeting"
	"github.com/kappusuton-yon-tebaru/backend/internal/config"
	"github.com/kappusuton-yon-tebaru/backend/internal/greeting"
	"github.com/kappusuton-yon-tebaru/backend/internal/logger"
)

// Injectors from wire.go:

func Initialize() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.New(configConfig)
	if err != nil {
		return nil, err
	}
	service := greeting.New()
	handler := greeting2.New(service)
	app := New(loggerLogger, configConfig, handler)
	return app, nil
}

// wire.go:

type App struct {
	Logger          *logger.Logger
	Config          *config.Config
	GreetingHandler *greeting2.Handler
}

func New(
	Logger *logger.Logger,
	Config *config.Config,
	GreetingHandler *greeting2.Handler,
) *App {
	return &App{
		Logger,
		Config,
		GreetingHandler,
	}
}
