// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package backend

import (
	auth2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/auth"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/build"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/deploy"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/dockerhub"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/ecr"
	githubapi2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/githubapi"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/greeting"
	image2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/image"
	job2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/job"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/monitoring"
	projectenv2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/projectenv"
	projectrepository2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/projectrepository"
	regproviders2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/regproviders"
	resource2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/resource"
	resourcerelationship2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/resourcerelationship"
	"github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/reverseproxy"
	role2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/role"
	svcdeploy2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/svcdeploy"
	svcdeployenv2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/svcdeployenv"
	user2 "github.com/kappusuton-yon-tebaru/backend/cmd/backend/internal/user"
	"github.com/kappusuton-yon-tebaru/backend/internal/auth"
	"github.com/kappusuton-yon-tebaru/backend/internal/config"
	"github.com/kappusuton-yon-tebaru/backend/internal/githubapi"
	"github.com/kappusuton-yon-tebaru/backend/internal/image"
	"github.com/kappusuton-yon-tebaru/backend/internal/job"
	"github.com/kappusuton-yon-tebaru/backend/internal/logger"
	"github.com/kappusuton-yon-tebaru/backend/internal/middleware"
	"github.com/kappusuton-yon-tebaru/backend/internal/mongodb"
	"github.com/kappusuton-yon-tebaru/backend/internal/projectenv"
	"github.com/kappusuton-yon-tebaru/backend/internal/projectrepository"
	"github.com/kappusuton-yon-tebaru/backend/internal/regproviders"
	"github.com/kappusuton-yon-tebaru/backend/internal/resource"
	"github.com/kappusuton-yon-tebaru/backend/internal/resourcerelationship"
	"github.com/kappusuton-yon-tebaru/backend/internal/rmq"
	"github.com/kappusuton-yon-tebaru/backend/internal/role"
	"github.com/kappusuton-yon-tebaru/backend/internal/svcdeploy"
	"github.com/kappusuton-yon-tebaru/backend/internal/svcdeployenv"
	"github.com/kappusuton-yon-tebaru/backend/internal/user"
	"github.com/kappusuton-yon-tebaru/backend/internal/validator"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func Initialize() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.New(configConfig)
	if err != nil {
		return nil, err
	}
	handler := greeting.New()
	database, err := mongodb.NewMongoDB(configConfig)
	if err != nil {
		return nil, err
	}
	repository := image.NewRepository(database)
	service := image.NewService(repository)
	imageHandler := image2.NewHandler(service)
	svcdeployRepository := svcdeploy.NewRepository(database)
	svcdeployService := svcdeploy.NewService(svcdeployRepository)
	svcdeployHandler := svcdeploy2.NewHandler(svcdeployService)
	svcdeployenvRepository := svcdeployenv.NewRepository(database)
	svcdeployenvService := svcdeployenv.NewService(svcdeployenvRepository)
	svcdeployenvHandler := svcdeployenv2.NewHandler(svcdeployenvService)
	userRepository, err := user.NewRepository(database)
	if err != nil {
		return nil, err
	}
	userService := user.NewService(userRepository, loggerLogger)
	validatorValidator, err := validator.New()
	if err != nil {
		return nil, err
	}
	userHandler := user2.NewHandler(userService, validatorValidator)
	resourceRepository := resource.NewRepository(database)
	resourcerelationshipRepository := resourcerelationship.NewRepository(database)
	resourceService := resource.NewService(resourceRepository, resourcerelationshipRepository)
	resourceHandler := resource2.NewHandler(resourceService, validatorValidator)
	roleRepository := role.NewRepository(database)
	roleService := role.NewService(roleRepository, userRepository)
	roleHandler := role2.NewHandler(roleService)
	projectrepositoryRepository := projectrepository.NewRepository(database)
	projectrepositoryService := projectrepository.NewService(projectrepositoryRepository)
	projectrepositoryHandler := projectrepository2.NewHandler(projectrepositoryService, validatorValidator)
	resourcerelationshipService := resourcerelationship.NewService(resourcerelationshipRepository)
	resourcerelationshipHandler := resourcerelationship2.NewHandler(resourcerelationshipService)
	jobRepository := job.NewRepository(database)
	jobService := job.NewService(jobRepository)
	jobHandler := job2.NewHandler(jobService, validatorValidator)
	regprovidersRepository, err := regproviders.NewRepository(database)
	if err != nil {
		return nil, err
	}
	regprovidersService := regproviders.NewService(regprovidersRepository)
	regprovidersHandler := regproviders2.NewHandler(regprovidersService, validatorValidator)
	projectenvRepository := projectenv.NewRepository(database)
	projectenvService := projectenv.NewService(projectenvRepository)
	projectenvHandler := projectenv2.NewHandler(projectenvService)
	ecrRepository := ecr.NewECRRepository()
	ecrService := ecr.NewService(ecrRepository)
	ecrHandler := ecr.NewHandler(ecrService, projectrepositoryService, validatorValidator)
	dockerHubRepository := dockerhub.NewDockerHubRepository(configConfig)
	dockerhubService := dockerhub.NewService(dockerHubRepository)
	dockerhubHandler := dockerhub.NewHandler(dockerhubService, projectrepositoryService)
	rmqRmq, err := rmq.New(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	buildService := build.NewService(rmqRmq, jobService, loggerLogger, projectrepositoryService)
	buildHandler := build.NewHandler(validatorValidator, buildService)
	monitoringHandler := monitoring.NewHandler(loggerLogger)
	reverseProxy, err := reverseproxy.New(configConfig)
	if err != nil {
		return nil, err
	}
	githubapiRepository := githubapi.NewRepository(configConfig)
	githubapiService := githubapi.NewService(githubapiRepository)
	githubapiHandler := githubapi2.NewHandler(configConfig, githubapiService, projectrepositoryService, resourceService, validatorValidator)
	deployService := deploy.NewService(rmqRmq, jobService, loggerLogger, projectrepositoryService, resourceService)
	deployHandler := deploy.NewHandler(deployService, validatorValidator)
	authRepository, err := auth.NewRepository(database)
	if err != nil {
		return nil, err
	}
	authService := auth.NewService(configConfig, authRepository, userRepository, loggerLogger)
	authHandler := auth2.NewHandler(configConfig, authService, validatorValidator)
	middlewareMiddleware := middleware.NewMiddleware(configConfig, authService, loggerLogger)
	app := New(loggerLogger, configConfig, handler, database, imageHandler, svcdeployHandler, svcdeployenvHandler, userHandler, resourceHandler, roleHandler, projectrepositoryHandler, resourcerelationshipHandler, jobHandler, regprovidersHandler, projectenvHandler, ecrHandler, dockerhubHandler, buildHandler, monitoringHandler, reverseProxy, githubapiHandler, deployHandler, authHandler, middlewareMiddleware)
	return app, nil
}

// wire.go:

type App struct {
	Logger                      *logger.Logger
	Config                      *config.Config
	GreetingHandler             *greeting.Handler
	MongoDatabase               *mongo.Database
	ImageHandler                *image2.Handler
	ServiceDeployment           *svcdeploy2.Handler
	ServiceDeploymentEnv        *svcdeployenv2.Handler
	UserHandler                 *user2.Handler
	ResourceHandler             *resource2.Handler
	RoleHandler                 *role2.Handler
	ProjectRepositoryHandler    *projectrepository2.Handler
	ResourceRelationshipHandler *resourcerelationship2.Handler
	JobHandler                  *job2.Handler
	RegisterProviderHandler     *regproviders2.Handler
	ProjectEnvironmentHandler   *projectenv2.Handler
	ECRHandler                  *ecr.Handler
	DockerHubHandler            *dockerhub.Handler
	BuildHandler                *build.Handler
	DeployHandler               *deploy.Handler
	MonitoringHandler           *monitoring.Handler
	ReverseProxyHandler         *reverseproxy.ReverseProxy
	GithubAPIHandler            *githubapi2.Handler
	AuthHandler                 *auth2.Handler
	Middleware                  *middleware.Middleware
}

func New(
	Logger *logger.Logger,
	Config *config.Config,
	GreetingHandler *greeting.Handler,
	MongoDatabase *mongo.Database,
	ImageHandler *image2.Handler,
	ServiceDeployment *svcdeploy2.Handler,
	ServiceDeploymentEnv *svcdeployenv2.Handler,
	UserHandler *user2.Handler,
	ResourceHandler *resource2.Handler,
	RoleHandler *role2.Handler,
	ProjectRepositoryHandler *projectrepository2.Handler,
	ResourceRelationshipHandler *resourcerelationship2.Handler,
	JobHandler *job2.Handler,
	RegisterProviderHandler *regproviders2.Handler,
	ProjectEnvironmentHandler *projectenv2.Handler,
	ECRHandler *ecr.Handler,
	DockerHubHandler *dockerhub.Handler,
	BuildHandler *build.Handler,
	MonitoringHandler *monitoring.Handler,
	ReverseProxyHandler *reverseproxy.ReverseProxy,
	GithubAPIHandler *githubapi2.Handler,
	DeployHandler *deploy.Handler,
	AuthHandler *auth2.Handler,
	Middleware *middleware.Middleware,
) *App {
	return &App{
		Logger,
		Config,
		GreetingHandler,
		MongoDatabase,
		ImageHandler,
		ServiceDeployment,
		ServiceDeploymentEnv,
		UserHandler,
		ResourceHandler,
		RoleHandler,
		ProjectRepositoryHandler,
		ResourceRelationshipHandler,
		JobHandler,
		RegisterProviderHandler,
		ProjectEnvironmentHandler,
		ECRHandler,
		DockerHubHandler,
		BuildHandler,
		DeployHandler,
		MonitoringHandler,
		ReverseProxyHandler,
		GithubAPIHandler,
		AuthHandler,
		Middleware,
	}
}
