// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package builderconsumer

import (
	build2 "github.com/kappusuton-yon-tebaru/backend/cmd/builder-consumer/internal/build"
	"github.com/kappusuton-yon-tebaru/backend/cmd/builder-consumer/internal/rmq"
	"github.com/kappusuton-yon-tebaru/backend/internal/build"
	"github.com/kappusuton-yon-tebaru/backend/internal/config"
	"github.com/kappusuton-yon-tebaru/backend/internal/kubernetes"
	"github.com/kappusuton-yon-tebaru/backend/internal/logger"
)

// Injectors from wire.go:

func Initialize() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.New(configConfig)
	if err != nil {
		return nil, err
	}
	kubernetesKubernetes, err := kubernetes.New(configConfig)
	if err != nil {
		return nil, err
	}
	rmqRmq, err := rmq.New(configConfig)
	if err != nil {
		return nil, err
	}
	service := build.NewService(configConfig, kubernetesKubernetes)
	handler := build2.NewHandler(loggerLogger, service)
	app := New(loggerLogger, configConfig, kubernetesKubernetes, rmqRmq, handler)
	return app, nil
}

// wire.go:

type App struct {
	Logger       *logger.Logger
	Config       *config.Config
	KubeClient   *kubernetes.Kubernetes
	RmqClient    *rmq.Rmq
	BuildHandler *build2.Handler
}

func New(
	Logger *logger.Logger,
	Config *config.Config,
	KubeClient *kubernetes.Kubernetes,
	RmqClient *rmq.Rmq,
	BuildHandler *build2.Handler,
) *App {
	return &App{
		Logger,
		Config,
		KubeClient,
		RmqClient,
		BuildHandler,
	}
}
